# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1280, 720)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.coding = QtWidgets.QLabel(Widget)
        self.coding.setGeometry(QtCore.QRect(4, 5, 331, 211))
        self.coding.setText("")
        self.coding.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\B.G_Template_1.gif"))
        self.coding.setScaledContents(True)
        self.coding.setObjectName("coding")
        self.jarvis = QtWidgets.QLabel(Widget)
        self.jarvis.setGeometry(QtCore.QRect(400, 70, 431, 91))
        self.jarvis.setText("")
        self.jarvis.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\jarvis.jpg"))
        self.jarvis.setObjectName("jarvis")
        self.ironman = QtWidgets.QLabel(Widget)
        self.ironman.setGeometry(QtCore.QRect(954, 5, 331, 701))
        self.ironman.setText("")
        self.ironman.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\pngwing.com (2).png"))
        self.ironman.setScaledContents(True)
        self.ironman.setObjectName("ironman")
        self.uicircle = QtWidgets.QLabel(Widget)
        self.uicircle.setGeometry(QtCore.QRect(430, 160, 401, 321))
        self.uicircle.setText("")
        self.uicircle.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\techcircle.gif"))
        self.uicircle.setScaledContents(True)
        self.uicircle.setObjectName("uicircle")
        self.loading = QtWidgets.QLabel(Widget)
        self.loading.setGeometry(QtCore.QRect(64, 275, 211, 201))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\tech loading-cropped.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.listeneing = QtWidgets.QLabel(Widget)
        self.listeneing.setGeometry(QtCore.QRect(64, 275, 211, 201))
        self.listeneing.setText("")
        self.listeneing.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\listening-1.gif"))
        self.listeneing.setScaledContents(True)
        self.listeneing.setObjectName("listeneing")
        self.recognition = QtWidgets.QLabel(Widget)
        self.recognition.setGeometry(QtCore.QRect(64, 275, 211, 201))
        self.recognition.setText("")
        self.recognition.setPixmap(QtGui.QPixmap("D:\\project\\Jarvis\\GUI files\\speaking.gif"))
        self.recognition.setScaledContents(True)
        self.recognition.setObjectName("recognition")
        self.terminalwindow = QtWidgets.QPlainTextEdit(Widget)
        self.terminalwindow.setGeometry(QtCore.QRect(3, 476, 941, 191))
        self.terminalwindow.setMouseTracking(True)
        self.terminalwindow.setTabletTracking(True)
        self.terminalwindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.terminalwindow.setReadOnly(True)
        self.terminalwindow.setOverwriteMode(True)
        self.terminalwindow.setBackgroundVisible(True)
        self.terminalwindow.setCenterOnScroll(True)
        self.terminalwindow.setObjectName("terminalwindow")
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setGeometry(QtCore.QRect(2, 671, 821, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.exit = QtWidgets.QPushButton(Widget)
        self.exit.setGeometry(QtCore.QRect(1030, 670, 121, 41))
        self.exit.setStyleSheet("border-image: url(D:/project/Jarvis/GUI files/exit(with border).png);")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.exit_2 = QtWidgets.QPushButton(Widget)
        self.exit_2.setGeometry(QtCore.QRect(830, 670, 131, 41))
        self.exit_2.setStyleSheet("border-image: url(D:/project/Jarvis/GUI files/enter(with border).png);")
        self.exit_2.setText("")
        self.exit_2.setObjectName("exit_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.terminalwindow.setPlaceholderText(_translate("Widget", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
